/**
 * Agent workflow type definitions.
 * 
 * These types define the agentic reasoning loop:
 * Plan → Decompose → Retrieve → Evaluate → Re-retrieve → Synthesize → Cite
 */

import type { Citation, ThinkingStep } from './chat';
import type { ScoredChunk } from './retrieval';

/** A sub-question generated by decomposing a complex question */
export interface SubQuestion {
  /** Unique identifier */
  id: string;
  /** The sub-question text */
  question: string;
  /** Why this sub-question is necessary */
  reasoning: string;
  /** Whether this sub-question has been answered */
  answered: boolean;
  /** Retrieved evidence for this sub-question */
  evidence?: ScoredChunk[];
  /** Generated answer for this sub-question */
  answer?: string;
}

/** The agent's plan for answering a question */
export interface AgentPlan {
  /** Original user question */
  originalQuestion: string;
  /** Whether the question is complex enough to decompose */
  isComplex: boolean;
  /** Sub-questions (if complex) */
  subQuestions: SubQuestion[];
  /** Strategy description */
  strategy: string;
  /** Estimated difficulty (1-5) */
  difficulty: number;
  /** Detected task intent for specialized workflow selection */
  taskIntent?: 'explain_all' | 'compare' | 'report' | 'insights' | 'quiz' | 'qa';
}

/** Possible actions the agent can take */
export type AgentActionType = 
  | 'plan'
  | 'decompose'
  | 'retrieve'
  | 'evaluate_evidence'
  | 're_retrieve'
  | 'synthesize'
  | 'cite_sources';

/** A single agent action with its result */
export interface AgentAction {
  /** Action type */
  type: AgentActionType;
  /** Input to this action */
  input: string;
  /** Output of this action */
  output: string;
  /** Time taken in milliseconds */
  durationMs: number;
  /** Whether this action succeeded */
  success: boolean;
}

/** Evidence quality evaluation result */
export interface EvidenceEvaluation {
  /** Overall quality score (0-1) */
  qualityScore: number;
  /** Whether evidence is sufficient to answer the question */
  isSufficient: boolean;
  /** Specific gaps identified in the evidence */
  gaps: string[];
  /** Suggestions for better retrieval */
  suggestions: string[];
}

/** Complete state of the agent during processing */
export interface AgentState {
  /** Current session ID */
  sessionId: string;
  /** The user's question */
  question: string;
  /** The generated plan */
  plan: AgentPlan | null;
  /** All actions taken so far */
  actions: AgentAction[];
  /** All thinking steps emitted */
  thinkingSteps: ThinkingStep[];
  /** All evidence gathered */
  evidence: ScoredChunk[];
  /** Evidence evaluation result */
  evaluation: EvidenceEvaluation | null;
  /** Final synthesized answer */
  answer: string | null;
  /** Source citations */
  citations: Citation[];
  /** Number of retrieval rounds performed */
  retrievalRounds: number;
  /** Maximum retrieval rounds allowed */
  maxRetrievalRounds: number;
  /** Whether processing is complete */
  isComplete: boolean;
  /** Error message if failed */
  error?: string;
}

/** Configuration for the agent orchestrator */
export interface AgentConfig {
  /** Maximum retrieval rounds before giving up */
  maxRetrievalRounds: number;
  /** Minimum evidence quality score to proceed */
  minEvidenceQuality: number;
  /** Whether to decompose complex questions */
  enableDecomposition: boolean;
  /** Whether to re-rank retrieved results */
  enableReranking: boolean;
  /** Whether to generate follow-up suggestions */
  enableSuggestions: boolean;
}

/** Default agent configuration */
export const DEFAULT_AGENT_CONFIG: AgentConfig = {
  maxRetrievalRounds: 3,
  minEvidenceQuality: 0.5,
  enableDecomposition: true,
  enableReranking: true,
  enableSuggestions: true,
};
